In [1]:
import pandas as pd
import gc

In [3]:
df_full = pd.read_csv('Human_BLCL.scores.tsv.gz', sep='\t', index_col=[0,1,2,3,4], header=[0,1])

/u/feghalya/.local/lib/python3.7/site-packages/numpy/lib/arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

In [4]:
df_full

                                                   BS                         \
                                           BaseScores NormScores Predictions
Dataset    Allele       N  Peptide   Class
Human_BLCL HLA-MinScore 1  VYNAVLELF True      0.0031   0.002701        True
                                     True      0.0031   0.002701        True
                           TESNLITSL True      0.0203   0.019910        True
                                     True      0.0203   0.019910        True
                           RLVDIGLDL False     0.1366   0.136268        True
...                                               ...        ...         ...
                        12 HMRFGFILH False     0.9846   0.984692       False
                           KEQGAVALW False     0.0032   0.002801        True
                                     False     0.0032   0.002801        True
                           LGKPFVAIL False     0.5365   0.536368       False
                                     False     0.5365   0.536368       False

                                                                         \
                                           PredictionsReduced    Scores
Dataset    Allele       N  Peptide   Class
Human_BLCL HLA-MinScore 1  VYNAVLELF True                True  0.741820
                                     True                True  0.741820
                           TESNLITSL True                True  0.729237
                                     True                True  0.729237
                           RLVDIGLDL False               True  0.634905
...                                                       ...       ...
                        12 HMRFGFILH False              False  0.065410
                           KEQGAVALW False               True  0.742413
                                     False               True  0.742413
                           LGKPFVAIL False              False  0.276511
                                     False              False  0.276511

                                                            BS-CAMAP  \
                                           ScoresReduced Predictions
Dataset    Allele       N  Peptide   Class
Human_BLCL HLA-MinScore 1  VYNAVLELF True       0.741820        True
                                     True       0.741820        True
                           TESNLITSL True       0.729237        True
                                     True       0.729237        True
                           RLVDIGLDL False      0.634905        True
...                                                  ...         ...
                        12 HMRFGFILH False      0.065410       False
                           KEQGAVALW False      0.742413        True
                                     False      0.742413        True
                           LGKPFVAIL False      0.276511       False
                                     False      0.276511       False

                                                                         \
                                           PredictionsReduced    Scores
Dataset    Allele       N  Peptide   Class
Human_BLCL HLA-MinScore 1  VYNAVLELF True                True  0.684736
                                     True                True  0.684736
                           TESNLITSL True                True  0.579641
                                     True                True  0.579641
                           RLVDIGLDL False               True  0.676995
...                                                       ...       ...
                        12 HMRFGFILH False              False  0.062886
                           KEQGAVALW False               True  0.710945
                                     False               True  0.710945
                           LGKPFVAIL False              False  0.235931
                                     False              False  0.235931

                                                          ...       TPM  \
                                           ScoresReduced  ...    Scores
Dataset    Allele       N  Peptide   Class                ...
Human_BLCL HLA-MinScore 1  VYNAVLELF True       0.684736  ...  0.777244
                                     True       0.684736  ...  0.681169
                           TESNLITSL True       0.579641  ...  0.512891
                                     True       0.579641  ...  0.712410
                           RLVDIGLDL False      0.776975  ...  0.170843
...                                                  ...  ...       ...
                        12 HMRFGFILH False      0.062886  ...  0.102542
                           KEQGAVALW False      0.710945  ...  0.336271
                                     False      0.710945  ...  0.322161
                           LGKPFVAIL False      0.235931  ...  0.162039
                                     False      0.235931  ...  0.221366

                                                           TPM-CAMAP  \
                                           ScoresReduced Predictions
Dataset    Allele       N  Peptide   Class
Human_BLCL HLA-MinScore 1  VYNAVLELF True       0.777244        True
                                     True       0.777244        True
                           TESNLITSL True       0.712410       False
                                     True       0.712410        True
                           RLVDIGLDL False      0.460424       False
...                                                  ...         ...
                        12 HMRFGFILH False      0.200621       False
                           KEQGAVALW False      0.336271       False
                                     False      0.336271       False
                           LGKPFVAIL False      0.221366       False
                                     False      0.221366       False

                                                                         \
                                           PredictionsReduced    Scores
Dataset    Allele       N  Peptide   Class
Human_BLCL HLA-MinScore 1  VYNAVLELF True                True  0.618876
                                     True                True  0.558900
                           TESNLITSL True                True  0.417676
                                     True                True  0.525069
                           RLVDIGLDL False               True  0.332866
...                                                       ...       ...
                        12 HMRFGFILH False              False  0.243187
                           KEQGAVALW False              False  0.395230
                                     False              False  0.387455
                           LGKPFVAIL False              False  0.278700
                                     False              False  0.319942

                                                         TPM-CAMAPShuff  \
                                           ScoresReduced    Predictions
Dataset    Allele       N  Peptide   Class
Human_BLCL HLA-MinScore 1  VYNAVLELF True       0.618876           True
                                     True       0.618876           True
                           TESNLITSL True       0.525069          False
                                     True       0.525069           True
                           RLVDIGLDL False      0.574084          False
...                                                  ...            ...
                        12 HMRFGFILH False      0.324467          False
                           KEQGAVALW False      0.395230           True
                                     False      0.395230           True
                           LGKPFVAIL False      0.319942          False
                                     False      0.319942          False

                                                                         \
                                           PredictionsReduced    Scores
Dataset    Allele       N  Peptide   Class
Human_BLCL HLA-MinScore 1  VYNAVLELF True                True  0.784138
                                     True                True  0.691621
                           TESNLITSL True                True  0.406572
                                     True                True  0.613708
                           RLVDIGLDL False               True  0.223943
...                                                       ...       ...
                        12 HMRFGFILH False              False  0.091911
                           KEQGAVALW False               True  0.521455
                                     False               True  0.505849
                           LGKPFVAIL False              False  0.146034
                                     False              False  0.199531


                                           ScoresReduced
Dataset    Allele       N  Peptide   Class
Human_BLCL HLA-MinScore 1  VYNAVLELF True       0.784138
                                     True       0.784138
                           TESNLITSL True       0.613708
                                     True       0.613708
                           RLVDIGLDL False      0.535682
...                                                  ...
                        12 HMRFGFILH False      0.179287
                           KEQGAVALW False      0.521455
                                     False      0.521455
                           LGKPFVAIL False      0.199531
                                     False      0.199531

[10957618 rows x 52 columns]

In [5]:
df_full = df_full.loc[:, (slice(None), 'ScoresReduced')]
df_full.columns = df_full.columns.droplevel(1)
df_full.index = df_full.index.droplevel([0,1])
gc.collect()

0

In [11]:
df_full

                          BS  BS-CAMAP  BS-CAMAPShuff    BS-TPM  BS-TPM-CAMAP  \
N  Peptide   Class
1  VYNAVLELF True   0.741820  0.684736       0.754625  0.907945      0.879694
             True   0.741820  0.684736       0.754625  0.907945      0.879694
   TESNLITSL True   0.729237  0.579641       0.626006  0.868157      0.778019
             True   0.729237  0.579641       0.626006  0.868157      0.778019
   RLVDIGLDL False  0.634905  0.776975       0.710401  0.597907      0.734524
...                      ...       ...            ...       ...           ...
12 HMRFGFILH False  0.065410  0.062886       0.055017  0.018523      0.018457
   KEQGAVALW False  0.742413  0.710945       0.870645  0.592110      0.563483
             False  0.742413  0.710945       0.870645  0.592110      0.563483
   LGKPFVAIL False  0.276511  0.235931       0.242627  0.101316      0.088162
             False  0.276511  0.235931       0.242627  0.101316      0.088162

                    BS-TPM-CAMAPShuff     CAMAP  CAMAPShuff       TPM  \
N  Peptide   Class
1  VYNAVLELF True            0.911568  0.430666    0.516312  0.777244
             True            0.911568  0.430666    0.516312  0.777244
   TESNLITSL True            0.807736  0.338605    0.383795  0.712410
             True            0.807736  0.338605    0.383795  0.712410
   RLVDIGLDL False           0.669177  0.666692    0.583857  0.460424
...                               ...       ...         ...       ...
12 HMRFGFILH False           0.016100  0.485194    0.473471  0.200621
   KEQGAVALW False           0.758473  0.460677    0.615126  0.336271
             False           0.758473  0.460677    0.615126  0.336271
   LGKPFVAIL False           0.089734  0.444635    0.475036  0.221366
             False           0.089734  0.444635    0.475036  0.221366

                    TPM-CAMAP  TPM-CAMAPShuff
N  Peptide   Class
1  VYNAVLELF True    0.618876        0.784138
             True    0.618876        0.784138
   TESNLITSL True    0.525069        0.613708
             True    0.525069        0.613708
   RLVDIGLDL False   0.574084        0.535682
...                       ...             ...
12 HMRFGFILH False   0.324467        0.179287
   KEQGAVALW False   0.395230        0.521455
             False   0.395230        0.521455
   LGKPFVAIL False   0.319942        0.199531
             False   0.319942        0.199531

[10957618 rows x 11 columns]

In [37]:
df_full

                          BS  BS-CAMAP  BS-CAMAPShuff    BS-TPM  BS-TPM-CAMAP  \
N  Peptide   Class
1  VYNAVLELF True   0.741820  0.684736       0.754625  0.907945      0.879694
             True   0.741820  0.684736       0.754625  0.907945      0.879694
   TESNLITSL True   0.729237  0.579641       0.626006  0.868157      0.778019
             True   0.729237  0.579641       0.626006  0.868157      0.778019
   RLVDIGLDL False  0.634905  0.776975       0.710401  0.597907      0.734524
...                      ...       ...            ...       ...           ...
12 HMRFGFILH False  0.065410  0.062886       0.055017  0.018523      0.018457
   KEQGAVALW False  0.742413  0.710945       0.870645  0.592110      0.563483
             False  0.742413  0.710945       0.870645  0.592110      0.563483
   LGKPFVAIL False  0.276511  0.235931       0.242627  0.101316      0.088162
             False  0.276511  0.235931       0.242627  0.101316      0.088162

                    BS-TPM-CAMAPShuff     CAMAP  CAMAPShuff       TPM  \
N  Peptide   Class
1  VYNAVLELF True            0.911568  0.430666    0.516312  0.777244
             True            0.911568  0.430666    0.516312  0.777244
   TESNLITSL True            0.807736  0.338605    0.383795  0.712410
             True            0.807736  0.338605    0.383795  0.712410
   RLVDIGLDL False           0.669177  0.666692    0.583857  0.460424
...                               ...       ...         ...       ...
12 HMRFGFILH False           0.016100  0.485194    0.473471  0.200621
   KEQGAVALW False           0.758473  0.460677    0.615126  0.336271
             False           0.758473  0.460677    0.615126  0.336271
   LGKPFVAIL False           0.089734  0.444635    0.475036  0.221366
             False           0.089734  0.444635    0.475036  0.221366

                    TPM-CAMAP  TPM-CAMAPShuff
N  Peptide   Class
1  VYNAVLELF True    0.618876        0.784138
             True    0.618876        0.784138
   TESNLITSL True    0.525069        0.613708
             True    0.525069        0.613708
   RLVDIGLDL False   0.574084        0.535682
...                       ...             ...
12 HMRFGFILH False   0.324467        0.179287
   KEQGAVALW False   0.395230        0.521455
             False   0.395230        0.521455
   LGKPFVAIL False   0.319942        0.199531
             False   0.319942        0.199531

[10957618 rows x 11 columns]

In [32]:
df = df_full.loc[(7, slice(None), slice(None)),:]

In [33]:
df = df.reset_index().drop_duplicates().set_index(['N', 'Peptide', 'Class'])

In [34]:
cs = df.reset_index().Class.sum()
ca = df.reset_index().Class.shape[0]
print(ca, cs)

490297 9039

In [35]:
prefixes = [
    'CAMAPShuff',
    'CAMAP',
    'TPM',
    'TPM-CAMAPShuff',
    'TPM-CAMAP',
    'BS-CAMAPShuff',
    'BS-CAMAP',
    'BS-TPM-CAMAPShuff',
    'BS',
    'BS-TPM',
    'BS-TPM-CAMAP'
]
proportions = [
    0.01,
    0.1,
    0.25,
    0.5,
    0.75,
    0.9,
    0.99
]

In [36]:
for proportion in proportions:
    print(proportion*100, '%', round(cs*proportion, 5))
    for prefix in prefixes:
        ccs = df[[prefix]].sort_values(prefix, ascending=False).reset_index().Class.cumsum()
        print(prefix, ':', ccs[ccs == int(cs*proportion)].index[0],
              round(ccs[ccs == int(cs*proportion)].index[0]/ca*100, 3), '%')
    print()

1.0 % 90.39
CAMAPShuff : 1818 0.371 %
CAMAP : 762 0.155 %
TPM : 237 0.048 %
TPM-CAMAPShuff : 116 0.024 %
TPM-CAMAP : 96 0.02 %
BS-CAMAPShuff : 353 0.072 %
BS-CAMAP : 255 0.052 %
BS-TPM-CAMAPShuff : 99 0.02 %
BS : 348 0.071 %
BS-TPM : 128 0.026 %
BS-TPM-CAMAP : 91 0.019 %

10.0 % 903.9
CAMAPShuff : 19740 4.026 %
CAMAP : 13721 2.799 %
TPM : 1758 0.359 %
TPM-CAMAPShuff : 1817 0.371 %
TPM-CAMAP : 1630 0.332 %
BS-CAMAPShuff : 5574 1.137 %
BS-CAMAP : 4421 0.902 %
BS-TPM-CAMAPShuff : 1194 0.244 %
BS : 4944 1.008 %
BS-TPM : 1184 0.241 %
BS-TPM-CAMAP : 1148 0.234 %

25.0 % 2259.75
CAMAPShuff : 57957 11.821 %
CAMAP : 44122 8.999 %
TPM : 6110 1.246 %
TPM-CAMAPShuff : 7045 1.437 %
TPM-CAMAP : 7060 1.44 %
BS-CAMAPShuff : 18509 3.775 %
BS-CAMAP : 15811 3.225 %
BS-TPM-CAMAPShuff : 4020 0.82 %
BS : 17958 3.663 %
BS-TPM : 3566 0.727 %
BS-TPM-CAMAP : 3905 0.796 %

50.0 % 4519.5
CAMAPShuff : 140023 28.559 %
CAMAP : 120317 24.54 %
TPM : 19397 3.956 %
TPM-CAMAPShuff : 24365 4.969 %
TPM-CAMAP : 27270 5.562 %
BS-CAMAPShuff : 56433 11.51 %
BS-CAMAP : 52162 10.639 %
BS-TPM-CAMAPShuff : 13418 2.737 %
BS : 56245 11.472 %
BS-TPM : 11332 2.311 %
BS-TPM-CAMAP : 14154 2.887 %

75.0 % 6779.25
CAMAPShuff : 262185 53.475 %
CAMAP : 246866 50.35 %
TPM : 56534 11.531 %
TPM-CAMAPShuff : 67580 13.783 %
TPM-CAMAP : 76023 15.505 %
BS-CAMAPShuff : 140121 28.579 %
BS-CAMAP : 137185 27.98 %
BS-TPM-CAMAPShuff : 43111 8.793 %
BS : 153197 31.246 %
BS-TPM : 41950 8.556 %
BS-TPM-CAMAP : 44437 9.063 %

90.0 % 8135.1
CAMAPShuff : 374725 76.428 %
CAMAP : 360215 73.469 %
TPM : 124482 25.389 %
TPM-CAMAPShuff : 140496 28.655 %
TPM-CAMAP : 147760 30.137 %
BS-CAMAPShuff : 269856 55.039 %
BS-CAMAP : 256297 52.274 %
BS-TPM-CAMAPShuff : 124703 25.434 %
BS : 302958 61.791 %
BS-TPM : 128209 26.149 %
BS-TPM-CAMAP : 120131 24.502 %

99.0 % 8948.61
CAMAPShuff : 470847 96.033 %
CAMAP : 470100 95.881 %
TPM : 384192 78.359 %
TPM-CAMAPShuff : 378122 77.121 %
TPM-CAMAP : 374187 76.318 %
BS-CAMAPShuff : 449416 91.662 %
BS-CAMAP : 443895 90.536 %
BS-TPM-CAMAPShuff : 362783 73.992 %
BS : 468466 95.547 %
BS-TPM : 365663 74.58 %
BS-TPM-CAMAP : 359623 73.348 %